%{"name" => "bAnaNa", "age" => "42"} |> Inmana.Welcomer.call()
%{"name" => "gEorGe", "age" => "21"} |> Inmana.Welcomer.call()
%{"name" => "gEorGe", "age" => "20"} |> Inmana.Welcomer.call()
%{"name" => "gEorGe"} |> Inmana.Welcomer.call()
%{} |> Inmana.Welcomer.call()
